title: {
    label: High level K3s architecture
    shape: text
    near: top-center
    style: {
        font-size: 55
    }
}

direction: right
homelab: homelab {
    style: {
        fill: transparent
        stroke-dash: 1
    }

    user: K3s user {
        shape: circle
        icon: https://icons.terrastruct.com/essentials%2F365-user.svg
    }

    k3s_servers: "K3s Servers" {

        grid-columns: 1
        server1: "Server node" {
            etcd: Embedded etcd {
                shape: cylinder
            }
        }
        server2: "Server node" {
            etcd: Embedded etcd {
                shape: cylinder
            }
        }
        server3: "Server node" {
            etcd: Embedded etcd {
                shape: cylinder
            }
        }

    }

    controlPlaneLb: KubeVip(Control plane LB)

    serviceLb: MetalLB (Service LB)  {

    }


    user -> controlPlaneLb: kubectl get pods
    controlPlaneLb -> k3s_servers
    k3s_servers -> serviceLb
}


